src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use App\Service\BlogService;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Blog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100000000)
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $modifiedAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVisible;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        $this->setSlug();

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDisplayContent(){
    $pattern = '/h1/i';
    $replacement = 'h2';
    return preg_replace($pattern, $replacement, $this->content);
}

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(): self
    {
        $this->slug = BlogService::slugify($this->title);

        return $this;
    }

    public function __toString(){
        return $this->title;
    }

    public function getModifiedAt(): ?\DateTimeInterface
    {
        return $this->modifiedAt;
    }

    public function setModifiedAt(\DateTimeInterface $modifiedAt): self
    {
        $this->modifiedAt = $modifiedAt;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function autoTimeStamp(): void
    {
        $this->setModifiedAt(new \DateTime('now'));

    }

    public function getIsVisible(): ?bool
    {
        return $this->isVisible;
    }

    public function setIsVisible(bool $isVisible): self
    {
        $this->isVisible = $isVisible;

        return $this;
    }
}

src/Entity/Portfolio.php
<?php

namespace App\Entity;

use App\Repository\PortfolioRepository;
use App\Service\BlogService;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PortfolioRepository::class)
 */
class Portfolio
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=10000000)
     */
    private $shortDescription;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $heading;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $link;




    /**
     * @ORM\ManyToOne(targetEntity=Image::class, inversedBy="portfolios")
     */
    private $featuredImage;

    /**
     * @ORM\ManyToMany(targetEntity=Image::class)
     */
    private $images;


    /**
     * @ORM\Column(type="string", length=10000)
     */
    private $finally;

    /**
     * @ORM\Column(type="array")
     */
    private $keywords = [];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $myWorkOnThisProject;

    /**
     * @ORM\ManyToMany(targetEntity=PortfolioTask::class)
     */
    private $task;

    /**
     * @ORM\ManyToMany(targetEntity=PortfolioNumbers::class)
     */
    private $numbers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @return mixed
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * @param mixed $link
     */
    public function setLink($link): void
    {
        $this->link = $link;
    }

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->numbers = new ArrayCollection();
        $this->task = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        $this->setSlug();

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->shortDescription;
    }

    public function setShortDescription(string $shortDescription): self
    {
        $this->shortDescription = $shortDescription;

        return $this;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(string $heading): self
    {
        $this->heading = $heading;

        return $this;
    }

    public function getFeaturedImage(): ?Image
    {
        return $this->featuredImage;
    }

    public function setFeaturedImage(?Image $featuredImage): self
    {
        $this->featuredImage = $featuredImage;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        $this->images->removeElement($image);

        return $this;
    }


    public function getFinally(): ?string
    {
        return $this->finally;
    }

    public function setFinally(string $finally): self
    {
        $this->finally = $finally;

        return $this;
    }

    public function getKeywords(): ?array
    {
        return $this->keywords;
    }

    public function setKeywords(array $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getStringKeyWords() : string
    {
        return implode('","',$this->keywords);
    }

    public function getMyWorkOnThisProject(): ?string
    {
        return $this->myWorkOnThisProject;
    }

    public function setMyWorkOnThisProject(string $myWorkOnThisProject): self
    {
        $this->myWorkOnThisProject = $myWorkOnThisProject;

        return $this;
    }

    /**
     * @return Collection|PortfolioTask[]
     */
    public function getTask(): Collection
    {
        return $this->task;
    }

    public function addTask(PortfolioTask $task): self
    {
        if (!$this->task->contains($task)) {
            $this->task[] = $task;
        }

        return $this;
    }

    public function removeTask(PortfolioTask $task): self
    {
        $this->task->removeElement($task);

        return $this;
    }

    /**
     * @return Collection|PortfolioNumbers[]
     */
    public function getNumbers(): Collection
    {
        return $this->numbers;
    }

    public function addNumber(PortfolioNumbers $number): self
    {
        if (!$this->numbers->contains($number)) {
            $this->numbers[] = $number;
        }

        return $this;
    }

    public function removeNumber(PortfolioNumbers $number): self
    {
        $this->numbers->removeElement($number);

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(): self
    {
        $this->slug = BlogService::slugify($this->title);

        return $this;
    }

    public function getDisplayShortDescription(){
        $pattern = '/h1/i';
        $replacement = 'h2';
        return preg_replace($pattern, $replacement, $this->shortDescription);
    }

    public function __toString(){
        return $this->title;
    }

}

src/Controller/WebsiteController.php
<?php

namespace App\Controller;

use App\Entity\Portfolio;
use App\Kernel;
use App\Repository\BlogRepository;
use App\Repository\PortfolioRepository;
use App\Repository\TestimonyRepository;
use App\Service\MailService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


class WebsiteController extends AbstractController
{




    /**
     * @Route("/contact", name="contact")
     */
    public function contact(Request $request,MailService $mailService)
    {
        if($request->request->get('email')){
            $email = $request->request->get('email');
            $nom = $request->request->get('nom');
            $prenom = $request->request->get('prenom');
            $message = $request->request->get('message');
            $mailService->sendMail($nom,$prenom,$email,$message);
            return $this->render('website/message.html.twig', [
                'message' => "Message envoyé, vous recevrez une réponse sous peu si une réponse est requise.",
                'slider1' => "Votre message est" ,
                'slider21' => "En cours d'envoi" ,
                'slider22' => "Envoyé" ,
                'slider23' => "Réceptionné"]);
        }
        else{
            return $this->render('website/contact.html.twig');
        }
    }


    /**
     * @Route("sent", name="mailSent")
     */
    public function messageEnvoye(){

    }

    /**
     * @Route("/bepatient", name="bePatient")
     */
    public function enCours(){
        //$message = "Bonjour Romain Cadarsi, vous avez reçu un message de" . $_POST['nom'] . $_POST['prenom'] . "\n Qui dit : \n " . $_POST['message'];
        //mail('dev@cadarsir.fr', 'Message client', $message);
        return $this->render('website/message.html.twig', [
            'message' => "Aïe, il semble que cette page n'est pas encore terminée , revenez bientôt pour la voir ! \n La patience est une vertu.",
            'slider1' => "Oups, cette page est" ,
            'slider21' => "Non disponible" ,
            'slider22' => "En création" ,
            'slider23' => "Prévu pour bientôt"]);
    }

    /**
     * @Route("/", name="home")
     */
    public function index(PortfolioRepository $portfolioRepository,TestimonyRepository $testimonyRepository)
    {
        $allPortfolios = $portfolioRepository->findBy([],['id' =>'DESC']);
        $allTestimony = $testimonyRepository->findBy([],['id' => 'DESC']);
        return $this->render('website/accueil.html.twig', [
            'portfolios' => $allPortfolios,
            'testimonies' => $allTestimony
        ]);
    }

    /**
     * @Route("/portfolio", name="allPortfolio")
     */
    public function allPortfolio(PortfolioRepository $portfolioRepository)
    {
        $allPortfolio = $portfolioRepository->findBy([],['id' => 'DESC']);
        return $this->render('website/portfolio.html.twig', [
            'portfolios' => $allPortfolio
        ]);
    }

    /**
     * @Route("/portfolio/{slug}", name="showPortfolio" , methods={"GET"})
     */
    public function showPortfolio(string $slug, PortfolioRepository $portfolioRepository)
    {
        $portfolio = $portfolioRepository->findOneBy(['slug' => $slug ]);
        return $this->render('website/portfolioBase.html.twig', [
            'p' => $portfolio
        ]);
    }

    /**
     * @Route("/blog", name="allBlog")
     */
    public function allBlog(BlogRepository $blogRepository)
    {
        $allblog = $blogRepository->findBy([],['id' => 'DESC']);
        return $this->render('website/blog.html.twig', [
            'blogs' => $allblog
        ]);
    }

    /**
     * @Route("/blog/{slug}", name="showBlog" , methods={"GET"})
     */
    public function showBlog(string $slug, BlogRepository $blogRepository)
    {
        $blog = $blogRepository->findOneBy(['slug' => $slug]);
        return $this->render('website/blogBase.html.twig', [
            'b' => $blog
        ]);
    }

    /**
     * @Route("/xhr/uploadImage", name="uploadImage")
     */
    public function uploadImage( Request $request, Kernel $kernel)
    {
        $uploadDirectory = 'images/embedImage/';
        $path = $kernel->getProjectDir().'/public/' . $uploadDirectory;
        echo($_FILES['file']['name']);
        $image = $path . basename($_FILES['file']['name']);
        move_uploaded_file($_FILES['file']['tmp_name'], $image);
        return $this->render('blank.html.twig');
    }

    /**
     * @Route("/xhr/getImages", name="getImages")
     */
    public function getImages( Kernel $kernel)
    {
        $uploadDirectory = 'images/embedImage';
        $path = $kernel->getProjectDir().'/public/' . $uploadDirectory;
        $files = array_diff(scandir($path), array('..', '.'));
        $htmlresponse = "";
        $urlpath = "/images/embedImage/";
        foreach ($files as $file){
            $htmlresponse .= '<img src="' . $urlpath . $file . '"> ';
        }
        return new Response($htmlresponse);
    }

    /**
     * @Route("/imageSandbox", name="imageSandbox")
     */
    public function imageSandbox()
    {
        return $this->render('dragAndDropSandbox.html.twig', [
            'metaDescription' => "a simple drag and drop images sandbox",
            'title' => 'Drag it, Drop it, Copy it!'
        ]);
    }

    /**
     * @Route("/imagesPost", name="imagePost")
     */
    public function imagePost(Request $request,KernelInterface $kernel): Response
    {
        $image = $kernel->getProjectDir().'/public/' .$request->get("key");
        if (move_uploaded_file($_FILES['file']['tmp_name'], $image)) {
            $mess =  "File is valid, and was successfully uploaded.\n";
        } else {
            $mess =  "Possible file upload attack!\n";
        }
        return new Response($mess);
    }















}

templates/website/accueil.html.twig
{% extends 'base.html.twig' %}

	{% block title %}Cadarsir - Développeur Web{% endblock %}

	{% block body %}
		<section class="home-slider ftco-degree-bg">

			<div class="slider-item">
				<div class="overlay"></div>
				<div class="container">

					<div class="row slider-text align-items-center justify-content-center">
						<div class="col-md-10 ftco-animate text-center">
							<h1 class="mb-4">J'adore
								<strong class="typewrite" data-period="4000" data-type='[ "Développer.", "Designer.", "Découvrir.", "Créer." ]'>
									<span class="wrap"></span>
								</strong>
							</h1>
							<p>Bonjour, je m'appelle Romain Cadarsi, jeune Développeur et Designer Web diplômé depuis peu. J'aime découvrir de nouveaux projets et aider les gens à les concrétiser.</p>
							<p><a href="https://www.youtube.com/watch?v=kodSvxXE_R0" class="btn btn-primary btn-outline-white px-4 py-3 popup-vimeo"><span class="ion-ios-play mr-2"></span> Regarder la vidéo</a></p>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- END slider -->

		<section class="ftco-section-featured ftco-animate">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="carousel owl-carousel">
							<img src="../../images/dashboard_full_1.png" class="img-fluid" alt="">
						</div>
					</div>
				</div>
			</div>
		</section>


		<section class="ftco-section ftco-degree-bg">
			<div class="container">
				<div class="row justify-content-center mb-5 pb-5">
					<div class="col-md-7 text-center heading-section ftco-animate">
						<span class="subheading">Mes Services</span>
						<h2>Un site Cadarsir c'est bien plus qu'un simple site !</h2>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 col-lg-3 d-flex align-self-stretch ftco-animate">
						<div class="media block-6 services d-block text-center">
							<div class="d-flex justify-content-center"><div class="icon color-1 d-flex justify-content-center mb-3"><span class="align-self-center icon-layers"></span></div></div>
							<div class="media-body p-2">
								<h3 class="heading">Votre vision des choses</h3>
								<p>Pour avoir le site de vos rêves, décrivez moi votre projet, votre style, vos attentes. Je me charge du reste.</p>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-lg-3 d-flex align-self-stretch ftco-animate">
						<div class="media block-6 services d-block text-center">
							<div class="d-flex justify-content-center"><div class="icon color-2 d-flex justify-content-center mb-3"><span class="align-self-center icon-gears"></span></div></div>
							<div class="media-body p-2">
								<h3 class="heading">Aussi complet que voulu</h3>
								<p>Vous voulez créer un site vitrine ou au contraire gérer toutes vos activités avec? Tout est possible.</p>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-lg-3 d-flex align-self-stretch ftco-animate">
						<div class="media block-6 services d-block text-center">
							<div class="d-flex justify-content-center"><div class="icon color-3 d-flex justify-content-center mb-3"><span class="align-self-center icon-paper-plane"></span></div></div>
							<div class="media-body p-2">
								<h3 class="heading">Une oreille attentive</h3>
								<p>Si quelque chose ne vous plaît pas, je me dois de le régler, la satisfaction du client passe avant tout.</p>
							</div>
						</div>
					</div>

					<div class="col-md-6 col-lg-3 d-flex align-self-stretch ftco-animate">
						<div class="media block-6 services d-block text-center">
							<div class="d-flex justify-content-center"><div class="icon color-4 d-flex justify-content-center mb-3"><span class="align-self-center icon-live_help"></span></div></div>
							<div class="media-body p-2">
								<h3 class="heading">Maintenabilité &amp; Support</h3>
								<p>Après avoir réalisé votre projet, qui contacter de mieux que le créateur du site lui même? Je reste à votre disposition même après la fin du projet ! </p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

		<section class="ftco-section-parallax ftco-degree-bg">
			<div class="parallax-img d-flex align-items-center">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-10 text-center heading-section heading-section-white ftco-animate">
							<h2 class="h1 font-weight-bold">Augmentez la visibilité de votre
								<strong class="typewrite" data-period="4000" data-type='[ "Association.", "Restaurant.", "Entreprise.", "Blog." ]'>
									<span class="wrap"></span>
								</strong> </h2>
							<p><a href="{{ path('contact') }}" class="btn btn-primary btn-outline-white mt-3 py-3 px-4">Me contacter</a></p>
						</div>
					</div>
				</div>
			</div>
		</section>

		<section class="ftco-section">
			<div class="container-fluid">
				<div class="row no-gutters justify-content-center mb-5 pb-5">
					<div class="col-md-7 text-center heading-section ftco-animate">
						<span class="subheading">Projets</span>
						<h2>Mes Projets Récents</h2>
					</div>
				</div>
				<div class="row no-gutters">
					{% for portfolio in portfolios %}
						<div class="portfolioBlock block-3 d-md-flex ftco-animate{% if loop.index % 2 %} reversed {% endif %}">
							<a href="{{ path('showPortfolio',{'slug' : portfolio.slug}) }}" class="image" style="background-image: url('{{ asset(portfolio.featuredImage.path) }}'); "></a>
							<div class="text">
								<h4 class="subheading">{{ portfolio.myWorkOnThisProject }}</h4>
								<h2 class="heading"><a href="{{ path('showPortfolio',{'slug' : portfolio.slug}) }}">{{ portfolio.title }}</a></h2>
								<div>{{ portfolio.displayShortDescription | u.truncate( 600, '...', false) |replace({'<div>': '', '</div>': ""}) | raw }}</div>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		</section>

		<section class="ftco-section testimony-section ftco-degree-bg">
			<div class="container">
				<div class="row justify-content-center mb-5 pb-5">
					<div class="col-md-7 text-center heading-section ftco-animate">
						<span class="subheading">Ce que disent les clients</span>
						<h2>Mes clients satisfaits disent : </h2>
					</div>
				</div>
				<div class="row ftco-animate">
					<div class="col-md-12">
						<div class="carousel-testimony owl-carousel ftco-owl">
							{% for testimony in testimonies %}
							<div class="item text-center">
								<div class="testimony-wrap p-4 pb-5">
									<div class="user-img mb-4" style="background-image: url('{{ asset(testimony.client.image.path) }}')">
	                    				<span class="quote d-flex align-items-center justify-content-center">
	                      					<i class="icon-quote-left"></i>
	                   					 </span>
									</div>
									<div class="text">
										<p class="mb-5">{{testimony.description}}</p>
										<p class="name">{{ testimony.client.name }}</p>
										<span class="position">{{ testimony.client.legalEntity.name }} - {{ testimony.client.job }}</span>
									</div>
								</div>
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</section>
		<section class="ftco-section ftco-counter ftco-degree-bg" id="section-counter">
			<div class="container">
				<div class="row justify-content-center mb-5 pb-5">
					<div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
						<h2>Mon expérience :</h2>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 col-lg-4 d-flex justify-content-center counter-wrap ftco-animate">
						<div class="block-18 text-center">
							<div class="text">
								<strong class="number" data-number="35">0</strong>
								<span>Clients satisfaits par leur projet </span>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-lg-4 d-flex justify-content-center counter-wrap ftco-animate">
						<div class="block-18 text-center">
							<div class="text">
								<strong class="number" data-number="3">0</strong>
								<span>Ans de Freelance</span>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-lg-4 d-flex justify-content-center counter-wrap ftco-animate">
						<div class="block-18 text-center">
							<div class="text">
								<strong class="number" data-number="1205">0</strong>
								<span>Cafés engloutis</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

	{% endblock %}

templates/website/blogBase.html.twig
{% extends 'base.html.twig' %}

{% block css %}
<style>
    .content * {
        color: #4e4e4e;
    }
    blockquote{
        background-color: #568fc1;
        border-radius: 10px;
        padding: 10px 10px 010px 10px;
        color: white !important;
        font-size: 17px;
        font-weight: 600;
        width: max-content;
    }
    blockquote::before{
        content: "";
        position: absolute;
        height: 3%;
        width: 5px;
        background-color: #568fc1;
        margin-left: -20px;
        margin-top: -10px;
        border-radius: 10px;
    }

    figcaption{
        color: gray;
        text-align: center;
        font-size: small;
    }

    figure>img{
        width: 100%;
        height: auto;
    }
    @media all and (max-width: 720px){
        blockquote{
            width: auto;
        }
    }

</style>
{% endblock %}

	{% block title %}Cadarsir - {{ b.title }}{% endblock %}

	{% block body %}
        <section class="home-slider">
            <div class="slider-item fullscreen">
                <div class="overlay"></div>
                <div class="container">

                    <div class="row slider-text align-items-center justify-content-center">
                        <div class="col-md-10 ftco-animate text-center">
                            <h1 class="mb-4">{{ b.title}}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END slider -->
        <section class="ftco-section ftco-degree-bg">
            <div class="container">
                <div class="row justify-content-center mb-5 pb-5">
                    <div class="col-md-7 text-center heading-section ftco-animate">
                        <h2>{{ b.title }}</h2>
                    </div>
                </div>
                <div class=" content ftco-animate">
                    {{ b.displayContent | raw }}

                </div>
            </div>
        </section>


    {% endblock %}

templates/website/message.html.twig
	{% extends 'base.html.twig' %}

	{% block title %}Contact{% endblock %}

	{% block body %}
	<section class="home-slider ftco-degree-bg">

		<div class="slider-item">
			<div class="overlay"></div>
			<div class="container">

				<div class="row slider-text align-items-center justify-content-center">
					<div class="col-md-10 ftco-animate text-center">
						<h1 class="mb-4">{{slider1}}
							<strong class="typewrite" data-period="4000" data-type= '[ "{{slider21}}", "{{slider22}}", "{{slider23}}"]'>
								<span class="wrap"></span>
							</strong>
							<p>{{message | raw}}</p>
						</h1>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- END slider -->

	

		{% endblock %}

templates/website/portfolioBase.html.twig
{% extends 'base.html.twig' %}
{% block menu %}
    {% include('cadarsir/include/menu.html.twig') with {'cooperationName' : p.title , 'cooperationLink' : p.link } %}
{% endblock %}

{% block css %}
{{ parent() }}
    <style>
        .overlay{
            background-image: url("{{ asset(p.featuredImage.path) }}") !important;
            background-repeat: no-repeat !important;
            background-size: cover !important;
        }
        .overlay::after{
            content: "";
            position: absolute;
            width: 100%;
            height: 100%;
            background-color: #1a100078;
        }

        .ftco-degree-bg.top:before {
            content: '';
            position: absolute;
            left: 0;
            top: -50px;
            overflow: visible;
            width: 100%;
            height: 120px;
            z-index: 0;
            -webkit-transform: skewY(4deg);
            -moz-transform: skewY(4deg);
            -ms-transform: skewY(4deg);
            -o-transform: skewY(4deg);
            transform: skewY(4deg);
            background-color: #fff; }
        .slider-item.fullscreen{
            height: 100vh !important;
        }
    </style>
{% endblock %}

	{% block title %}Cadarsir - {{ p.title }}{% endblock %}

	{% block body %}
        <section class="home-slider">

            <div class="slider-item fullscreen">
                <div class="overlay"></div>
                <div class="container">

                    <div class="row slider-text align-items-center justify-content-center">
                        <div class="col-md-10 ftco-animate text-center">
                            <h1 class="mb-4">{{ p.title }} :
                                <strong class="typewrite" data-period="4000" data-type='[ "{{ p.stringKeyWords }}" ]'>
                                    <span class="wrap"></span>
                                </strong>
                            </h1>
                            <p>{{ p.heading }}</p>
                            <a href="{{ p.link }}" class ="buttonPage"> Voir le site </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END slider -->
        <section class="ftco-section ftco-degree-bg">
            <div class="container">
                <div class="row justify-content-center mb-5 pb-5">
                    <div class="col-md-7 text-center heading-section ftco-animate">
                        <span class="subheading">Description Rapide</span>
                        <h2>{{ p.title }}, C'est quoi ? </h2>
                    </div>
                </div>
                <div class="">
                    {{ p.displayShortDescription | raw }}

                </div>
            </div>
        </section>

        <section class="ftco-section ftco-counter ftco-degree-bg" id="section-counter">
            <div class="container">
                <div class="row justify-content-center mb-5 pb-5">
                    <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
                        <h2>Quelques chiffres de ce projet :</h2>
                    </div>
                </div>
                <div class="row">
                    {% for number in p.numbers %}
                    <div class="col-md-6 col-lg-4 d-flex justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center">
                            <div class="text">
                                <strong class="number" data-number="{{ number.chiffre }}">0</strong>
                                <span>{{ number.description }}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </section>

        <section class="ftco-section ftco-degree-bg">
            <div class="container">
                <div class="row justify-content-center mb-5 pb-5">
                    <div class="col-md-7 text-center heading-section ftco-animate">
                        <span class="subheading">Mon travail sur ce projet</span>
                        <h2>{{p.myWorkOnThisProject}}</h2>
                    </div>
                </div>
                <div class="row">
                    {% for task in p.task %}
                    <div class="col-md-6 col-lg-3 d-flex align-self-stretch ftco-animate">
                        <div class="media block-6 services d-block text-center">
                            <div class="d-flex justify-content-center"><div class="icon color-{{ loop.index}} d-flex justify-content-center mb-3"><span class="align-self-center fa fa-{{ task.icon }}"></span></div></div>
                            <div class="media-body p-2">
                                <h3 class="heading">{{ task.title }}</h3>
                                <p>{{task.description}}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </section>


        <section class="ftco-section ftco-counter ftco-degree-bg top" id="section-counter">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="mb-4" style="color:white; font-weight : 200"> Plus d'images </h1>
                        <div class="carousel owl-carousel">
                            {% for image in p.images %}
                            <div class="">
                                <img src="{{ asset(image.path) }}" class="img-fluid" alt="">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="ftco-section ftco-degree-bg">
            <div class="container">
                <div class="row justify-content-center mb-5 pb-5">
                    <div class="col-md-7 text-center heading-section ftco-animate">
                        <h2>Que m'a apporté ce projet ?</h2>
                    </div>
                </div>
                <div class="finally">
                    {{ p.finally | raw }}
                </div>
            </div>
        </section>
    {% endblock %}